### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by caprice** [aohanyao/ViewPagerCardTransformer#1]
目前demo中是所有item都层叠起来，而我只想一次层叠3个item，  改成vpMain.setOffscreenPageLimit(3);这样似乎是可以，可是这样后往前滑后就是显示4层，往后是3层。请问我该如何解决呢，期待你的回复

**Comment by aohanyao** [comment]
最近比较忙，推荐你看看这个：https://github.com/DingMouRen/LayoutManagerGroup
使用RecyclerView来完成

**Comment by aohanyao** [comment]
我后续再看看怎么适配你说的这种情况。

**Comment by aohanyao** [comment]
好像那个也不能实现你的需求。

**Comment by caprice** [comment]
非常感谢！

**Comment by caprice** [comment]
还是你这个更贴合我的需求啊，试了下你推荐的项目用layoutmanager始终做不到我要的效果。

**Comment by caprice** [comment]
今天修改你这个已经达到了我想要的效果，控制3张卡片的显示。
1.  vpMain.setOffscreenPageLimit(3);
2. 在CardPageTransformer::transformHorizontal中添加条件：
   ```
   else if (position <= 2) {    //只显示3张卡片

            setHorizontalTransformPager(page, position);
            //屏蔽点击事件
            page.setClickable(false);
        } else {
            page.setTranslationX(0f);
            page.setTranslationY(0f);
        }
```

**Comment by aohanyao** [comment]
非常感谢你提供的代码和思路！！！
