### ISSUE TITLE
快速滑动会产生偏移

### ISSUE THREAD

**Issue by wangchang163** [aohanyao/ViewPagerCardTransformer#2]
不知道dalao有没有发现，设置层叠效果在top或者bottom的时候，来回滑动太快，viewpager的顶边或底边会出现位置偏移

**Comment by farley-fu** [comment]
https://github.com/aohanyao/ViewPagerCardTransformer/issues/2#issue-394558041

无语。。。上个动画没有走完，下个动画又开始了。所以造成位置偏移，从而给人的感官很不好

**Comment by aohanyao** [comment]
1.2 版本已修复完成，抱歉~
